/**
 * LogTint - content script.
 *
 * Detects text nodes containing ANSI sequences and replaces them with
 * colored HTML, in real time, using a MutationObserver for new content
 * (streaming logs) plus an initial scan of already-present content.
 */
(function () {
  "use strict";

  if (window.__logTintLoaded) return;
  window.__logTintLoaded = true;

  const TAG_SKIP = new Set(["SCRIPT", "STYLE", "TEXTAREA", "INPUT", "NOSCRIPT"]);

  let enabled = true;
  let pending = new Set();
  let rafScheduled = false;

  // Ace editors (or other widgets with their own render loop) already
  // hooked, so we don't register the "afterRender" listener more than
  // once per instance.
  const hookedAceEditors = new WeakSet();

  // Original text (with the ANSI codes intact) for each rendered <span>,
  // so we can revert to the exact plain text when LogTint is disabled.
  const originalTextByWrapper = new WeakMap();

  function getHostname() {
    try {
      return location.hostname;
    } catch (e) {
      return "";
    }
  }

  function shouldSkipElement(el) {
    while (el) {
      if (el.nodeType === Node.ELEMENT_NODE) {
        if (TAG_SKIP.has(el.tagName)) return true;
        if (el.isContentEditable) return true;
      }
      el = el.parentNode;
    }
    return false;
  }

  // Replaces a text node with the equivalent colored HTML.
  function processTextNode(node) {
    if (!enabled) return;
    if (!node || node.nodeType !== Node.TEXT_NODE) return;
    const parent = node.parentNode;
    if (!parent) return;
    if (shouldSkipElement(parent)) return;

    const text = node.nodeValue;
    if (!text || !window.LogTint.containsAnsi(text)) return;

    const html = window.LogTint.ansiToHtml(text);
    if (html === null) return;

    const wrapper = document.createElement("span");
    wrapper.className = "logtint-line";
    // The HTML generated by ansiToHtml escapes all user text; it only
    // introduces <span style="..."> markup that we control ourselves.
    wrapper.innerHTML = html;
    originalTextByWrapper.set(wrapper, text);
    parent.replaceChild(wrapper, node);
  }

  // Walks a subtree looking for text nodes containing ANSI codes.
  function scanSubtree(root) {
    if (!root) return;
    if (root.nodeType === Node.TEXT_NODE) {
      processTextNode(root);
      return;
    }
    if (root.nodeType !== Node.ELEMENT_NODE && root.nodeType !== Node.DOCUMENT_FRAGMENT_NODE) {
      return;
    }
    if (root.nodeType === Node.ELEMENT_NODE && TAG_SKIP.has(root.tagName)) return;

    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT, {
      acceptNode(n) {
        return shouldSkipElement(n.parentNode)
          ? NodeFilter.FILTER_REJECT
          : NodeFilter.FILTER_ACCEPT;
      }
    });

    const nodes = [];
    let n;
    while ((n = walker.nextNode())) nodes.push(n);
    // Process after collecting, so we don't mutate the tree while walking it.
    nodes.forEach(processTextNode);
  }

  function flushPending() {
    rafScheduled = false;
    const targets = pending;
    pending = new Set();
    targets.forEach(scanSubtree);
  }

  // Restores the original text (with the ANSI codes intact) of every
  // already-rendered line, so disabling LogTint takes effect instantly
  // without needing to reload the page.
  function revertPaintedNodes(root) {
    const scope = root && typeof root.querySelectorAll === "function" ? root : document;
    const wrappers = scope.querySelectorAll(".logtint-line");
    wrappers.forEach((wrapper) => {
      const original = originalTextByWrapper.get(wrapper);
      if (original === undefined) return;
      originalTextByWrapper.delete(wrapper);
      const textNode = document.createTextNode(original);
      wrapper.replaceWith(textNode);
    });
  }

  // --- Ace Editor integration ----------------------------------------------
  //
  // Ace Editor (and similar widgets with their own "render loop") manage
  // their own DOM: they virtualize the visible lines and regenerate them
  // from their internal document model on every repaint (scroll, new
  // lines, etc.). If we only relied on MutationObserver, Ace could
  // overwrite our colored HTML in the same frame we inserted it, giving
  // the impression that "nothing is rendered". The fix is to hook into
  // Ace's own event ("afterRender") and reprocess right after each of its
  // repaints, instead of competing with it.
  //
  // Ace exposes the editor instance as `container.env.editor` on the same
  // DOM element passed to `ace.edit(container)`. Since content scripts
  // share DOM nodes with the page (only the JS scope is isolated), we can
  // read that property without any special privileges.
  function tryHookAceEditor(container, attemptsLeft) {
    if (hookedAceEditors.has(container)) return;

    const env = container.env;
    const editor = env && env.editor;
    const renderer = editor && editor.renderer;

    if (!renderer || typeof renderer.on !== "function") {
      // The editor may take a tick to initialize after the container is
      // inserted into the DOM; retry a few times.
      if (attemptsLeft > 0) {
        setTimeout(() => tryHookAceEditor(container, attemptsLeft - 1), 150);
      } else {
        console.debug("[LogTint] Ace editor detected but could not hook into it (env.editor unavailable)", container);
      }
      return;
    }

    hookedAceEditors.add(container);
    const rescan = () => scanSubtree(container);
    renderer.on("afterRender", rescan);
    rescan();
    console.debug("[LogTint] Ace editor detected and hooked into afterRender", container);
  }

  function hookAceEditorsIn(root) {
    if (!root || typeof root.querySelectorAll !== "function") {
      // The node itself may be the editor (e.g. when added directly,
      // without a common ancestor captured by querySelectorAll).
      if (root && root.classList && root.classList.contains("ace_editor")) {
        tryHookAceEditor(root, 10);
      }
      return;
    }
    if (root.classList && root.classList.contains("ace_editor")) {
      tryHookAceEditor(root, 10);
    }
    root.querySelectorAll(".ace_editor").forEach((el) => tryHookAceEditor(el, 10));
  }

  function scheduleScan(node) {
    pending.add(node);
    if (!rafScheduled) {
      rafScheduled = true;
      requestAnimationFrame(flushPending);
    }
  }

  const observer = new MutationObserver((mutations) => {
    if (!enabled) return;
    for (const mutation of mutations) {
      if (mutation.type === "childList") {
        mutation.addedNodes.forEach((node) => {
          scheduleScan(node);
          if (node.nodeType === Node.ELEMENT_NODE) hookAceEditorsIn(node);
        });
      } else if (mutation.type === "characterData") {
        scheduleScan(mutation.target);
      }
    }
  });

  function startObserving() {
    observer.observe(document.documentElement || document.body, {
      childList: true,
      characterData: true,
      subtree: true
    });
  }

  function stopObserving() {
    observer.disconnect();
  }

  function initialScan() {
    scanSubtree(document.body);
    hookAceEditorsIn(document.body);
  }

  function applyEnabledState(nextEnabled) {
    enabled = nextEnabled;
    if (enabled) {
      initialScan();
      startObserving();
    } else {
      stopObserving();
      revertPaintedNodes(document);
    }
  }

  function loadSettingsAndStart() {
    chrome.storage.local.get(
      { globalEnabled: true, disabledHosts: [] },
      (settings) => {
        const host = getHostname();
        const isDisabledHere = settings.disabledHosts.includes(host);
        applyEnabledState(settings.globalEnabled && !isDisabledHere);
      }
    );
  }

  // Reacts to configuration changes coming from the popup in real time.
  chrome.storage.onChanged.addListener((changes, area) => {
    if (area !== "local") return;
    if (!("globalEnabled" in changes) && !("disabledHosts" in changes)) return;
    loadSettingsAndStart();
  });

  // API exposed to the popup (on-demand manual re-scan).
  window.__logTint = {
    rescan: initialScan,
    isEnabled: () => enabled
  };

  loadSettingsAndStart();
})();
